# Generated by Django 5.2.17 on 2026-08-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, help_text='External URL (e.g. https://simpleplanner.blottogbar.no)')),
                ('ascii_icon', models.TextField(blank=True, help_text='Monospace ASCII icon / badge')),
                ('status', models.CharField(choices=[('live', 'Live in Production'), ('beta', 'In Beta'), ('upcoming', 'Coming Soon'), ('concept', 'Concept')], default='live', max_length=20)),
                ('badge_label', models.CharField(blank=True, default='Live', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Showcase App',
                'verbose_name_plural': 'Showcase Apps',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
